### ISSUE TITLE
Working with Material Design Icons

### ISSUE THREAD

**Issue by newswim** [nathantreid/meteor-react-toolbox-example#2]
Right now I'm using React-Helmet and pulling in the Material Icons font from google. I'm wondering if there might be a better method, thanks!

**Comment by ddeklerk** [comment]
Is there something wrong with the method that is used in this example? If you don't want the Blaze package included in your app, you should use [static-html](https://atmospherejs.com/meteor/static-html).

**Comment by akanix42** [comment]
@newswim did you figure this one out? If not, it's probably best asked on the Meteor forums (I've played around with React, but I'm all that familiar with it).

**Comment by newswim** [comment]
I think there are a few ways to bring this in, now that non-.js imports are supported. For what i'm doing, React Helmet is fine and gives me a good degree of control. I'll move the discussion there and close this issue. Thank you!!
