### ISSUE TITLE
Can´t run the example in Meteor 1.3.1

### ISSUE THREAD

**Issue by santiagopuentep** [nathantreid/meteor-react-toolbox-example#3]
I´m getting the following error when running the example. 

While loading plugin `mss` from package `nathantreid:css-modules`:
   fs.js:439:18: ENOENT, no such file or directory
   'C:\Users\santiago\Desktop\meteor-react-toolbox-example-master\meteor-react-toolbox-example-master\node_modules\react-toolbox\lib_colors.scss'

I couldn´t make it run with any of the instructions.

Please help!

**Comment by akanix42** [comment]
I'll be glad to help - please provide a github repo with the issue, and I'll take a look to see what's going on. :smile:

**Comment by santiagopuentep** [comment]
Thanks Nathan.

It´s simply checking out this repo ([Meteor-react-toolbox-example](https://github.com/nathantreid/meteor-react-toolbox-example)) and running "npm install && meteor" on it.

I´m using meteor 1.3.1 on Windows and not much more than that.

I´m getting:

"Uncaught Error: Cannot find module './style'" on "meteorInstall.node_modules.react-toolbox.lib.app_bar.AppBar.js" line 876.

Don´t worry about the other error "while loading plugin mss", it was my mistake.

**Comment by santiagopuentep** [comment]
Hi Nathan.

Any ideas on what could be wrong? Sorry to insist, I would really love to use the toolbox in my project!

**Comment by akanix42** [comment]
My apologies - it looks like I just needed to update this to the latest version of my CSS modules plugin.

Please try again, it should work this time. You can update your local version by running `meteor update nathantreid:css-modules`. Also make you sure you run `meteor npm install` instead of `npm install` (I've updated the documentation to reflect this).

**Comment by santiagopuentep** [comment]
Now it works! Thanks!

Do you mind answering one last question? What would be the difference between "meteor npm install" and "npm install"? I thought they were the same.

**Comment by akanix42** [comment]
`npm install` is dependent on your installed version of npm, whereas `meteor npm install` uses the version of npm that meteor uses internally. On my computer right now with node 5.1.1 installed, `npm --version` displays 3.3.12 and `meteor npm --version` outputs 2.14.22.

For react-toolbox and this demo, if you have npm 3+ installed you have to manually install normalize.css and some other react-toolbox dependencies. Npm 2 automatically downloads them.

**Comment by santiagopuentep** [comment]
Thanks for the clarification!
