### ISSUE TITLE
Support for latest Meteor and css-modules

### ISSUE THREAD

**Issue by gadicc** [nathantreid/meteor-react-toolbox-example#4]
Hey @nathantreid, I thought it might be better to track all this stuff here.  I'm going to close https://github.com/nathantreid/meteor-css-modules/issues/23.

Starting point, clone this repo, `meteor npm install && meteor`, everything works.  Then:

```
$ meteor update

Changes to your project's package version selections from updating the release:                                              
....
meteor-react-toolbox-example: updated to Meteor 1.3.2.4.

Changes to your project's package version selections from updating package
versions:

nathantreid:css-modules                      upgraded from 1.1.0 to 1.1.1
nathantreid:css-modules-import-path-helpers  upgraded from 0.1.1 to 0.1.2
```

I then get the error I mentioned previously:

```
TypeError: Cannot call method 'substr' of undefined
```

so I remove from `package.json`:

```
    "explicitIncludes": [
      "node_modules/react-toolbox"
    ]
```

and then get:

<details>
<summary>

`Error: Attempting to combine different files: client/components/style.scss`</summary>

```
Error: Attempting to combine different files:
{ type: 'js',
  sourcePath: 'client/components/style.scss',
  servePath: 'client/components/style.scss',
  installPath: 'client/components/style.scss',
  deps: { './style.css': {} },
  lazy: true,
  data: <Buffer 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 72 65 71 75 69 72 65 28 22 2e 2f 73 74 79 6c 65 2e 63 73 73 22 29 3b 0a>,
  hash: '39511a6d70e7980cb52ca5519c549245aa450762' }
{ type: 'js',
  data: <Buffer 65 78 70 6f 72 74 73 2e 5f 5f 65 73 4d 6f 64 75 6c 65 20 3d 20 74 72 75 65 3b 0a 0a 0a 76 61 72 20 73 74 79 6c 65 73 20 3d 20 7b 20 22 61 70 70 62 61 72 ...>,
  sourcePath: 'client/components/style.scss',
  targetPath: 'client/components/style.scss',
  servePath: '/client/components/style.scss',
  hash: '99665ead3d2ee3f773ebd07ee0c0d9f6079a1c55',
  sourceMap: undefined,
  lazy: false,
  bare: false,
  mainModule: false,
  imported: true,
  installPath: 'client/components/style.scss' }

    at checkProperty (/tools/isobuild/import-scanner.js:274:15)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:263:35)
    at /tools/isobuild/import-scanner.js:187:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:158:11)
    at /tools/isobuild/compiler-plugin.js:834:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:805:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2474:14
    at /tools/isobuild/bundler.js:2563:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/dragon/.meteor/packages/meteor-tool/.1.3.2_4.175ert8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2562:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

</details>

Not sure what else I can try from here.

On my real project, I don't get this error.  Even after removing `explicitIncludes`, I'm still stuck with the `substr` error.  But I'll look at that separately.

Thanks for the help!

**Comment by akanix42** [comment]
Meteor 1.3.2 changes the way css files are imported. :frowning: I've got some more digging to do, but for now you can make the example work by changing the `outputJsFilePath` option in package.json:

``` json
"cssModules": {
  "outputJsFilePath": "{dirname}/{basename}.js"
}
```

This issue affects the whole of my CSS modules plugin, see nathantreid/meteor-css-modules#24.

**Comment by newswim** [comment]
this is probably dumb, but @gadicc how did you make that code block collapsable? V cool.

**Comment by gadicc** [comment]
Thanks, @nathantreid!  I got past the "attempting to combine different files" problem but then was back with to original `substr` (from sourceMap) crash.  I just commented out [this line](https://github.com/nathantreid/meteor-css-modules/blob/4cbd6bdf9f371f7253b7937fd7072eccbdd350ac/css-modules-build-plugin.js#L229) and everything works again, didn't investigate any further yet.

Btw, what are your thoughts about ditching `addStyleSheet` and shipping each style sheet in it's own module via `addJavaScript` along with the other code you have to have there anyways?  From that point I think we're just 2 steps away from hotloading support :)  Only downside I can think of is missing out on some css-specific minification optimizations.

@newswim, haha, everyone (including me) has the same reaction when they see it for the first time.  Read [this](https://forums.meteor.com/t/mdg-plan-for-a-tracking-package/19471/13?u=gadicc), the "discourse expandable post" link in the next post, and the comments in the post after that.

**Comment by gadicc** [comment]
@nathantreid we can move this back to my original issue if it's more relevant there.

**Comment by akanix42** [comment]
This is probably more relevant in the other issue, but I'm fine with just continuing it here. 

I can't totally ditch `addStylesheet` since I actually need to have the CSS file for some of my apps, although I'm open to making it optional - the `addStylesheet` call is only used for non-lazy stylesheets; each lazy-loaded stylesheet is already "in it's own module via `addJavaScript` along with the other code", so that would be a pretty simple switch to add. The question then becomes which to make the default.

If we got hotloading working, I'd definitely turn that on for my development process!

The primary downside is if you use SSR, the styles won't load until the JS does.

Oh, and I had the same reaction to the collapsible code block you have up there!

**Comment by newswim** [comment]
fyi, this is how the hidden code trick is done:

``` html
<details> 
  <summary>Q1: What is the best Language in the World? </summary>
   A1: JavaScript 
</details>
```
