### ISSUE TITLE
import Dialog gets error

### ISSUE THREAD

**Issue by hervejegou** [nathantreid/meteor-react-toolbox-example#6]
Hi Nathan: I am using meteor with react-toolbox and css modules and mostly it works great. While trying to use the Dialog component I got error `Cannot find module './style.scss'` after importing Dialog component. Cant find ways to fix it so any help or pointer would be great.

Replicate the error using your template:
1.  download, install and using template with no modifications
2. only add `import Dialog from 'react-toolbox/lib/dialog';` to client/components/index.jsx and reload

=> get the error:  `Cannot find module './style.scss'`

It seems the failure to load occurs in Dialog.js component. I cannot find ways to fix that??
Here is the full error log:

```
install.js:78Uncaught Error: Cannot find module './style.scss'require @ install.js:78meteorInstall.node_modules.react-toolbox.lib.dialog.Dialog.js @ Dialog.js:25fileEvaluate @ install.js:141require @ install.js:75meteorInstall.node_modules.react-toolbox.lib.dialog.index.js @ index.js:8fileEvaluate @ install.js:141require @ install.js:75meteorInstall.client.index.jsx @ index.jsx:5fileEvaluate @ install.js:141require @ install.js:75(anonymous function) @ app.js?hash=888aa27…:191
```

**Comment by hervejegou** [comment]
Hi Nathan: UPDATED
it seems that the error is with dialog component only. I tried to import DatePicker (which relies on dialog component) and it gives the same error likely because it tries to load dialog component...
Dialog.js fails at line 25:  `var _style = require('./style.scss');`

I found a workaround for now:
- copy the dialog/style.scss file to another folder  in my project ie  '/imports/ui/client/fix/style.scss'
- import it in Dialog.js at line 25: `var _style = require('/imports/ui/client/fix/style.scss');`

Then it all works again... I am using a lot of other react-toolbox components with your setup and do not get errors.

We still have to include all style.scss in a parent client folder to avoid errors: this issue is reported in [css-modules - issue 29](https://github.com/nathantreid/meteor-css-modules/issues/29)

**Comment by tatomyr** [comment]
Hi to all. 
I currently have a similar problem. If I'm trying to import a react-toolbox element (for example - Checkbox or Switch or something another), I get an error "Cannot find module './theme.scss'" in ripple/index.js `require('./theme.scss')` despite of file presence  exactly in this folder. An error persists even  if I try to copy the 'theme.scss' into another folder outside the node_modules (with simultaneous replacing of the path in index file).
Jolt me please to the right direction.

**Comment by akanix42** [comment]
Oops, I dropped the ball on this one.. there have been a lot of changes since then, are you still experiencing this issue?

**Comment by hervejegou** [comment]
@nathantreid : yes I updated to latest version and it works great now... bug is gone... thanks.
