### ISSUE TITLE
Styling does not work with Meteor 1.3.3 and react-toolbox 1.0.0

### ISSUE THREAD

**Issue by ddeklerk** [nathantreid/meteor-react-toolbox-example#7]
I tried to update to the latest version for both Meteor and my NPM dependencies today, and I found out that the styling for the react-toolbox components no longer gets applied. Then I did the same thing, but this time in a clone of this repo and I had the same results.

I suspect that the way css is applied in react-toolbox 1.0.0 has changed. In the react-toolbox-example repo, the css is applied with a there property.

**Comment by pszynk** [comment]
if you want to use newer version of react-toolbox take a look at my pull request #8. Hope it will work for you.

**Comment by newswim** [comment]
Thanks @pszynk - this is super appreciated.
